-------------------------------------------------------------------------------
Test set: models.dao.Sql2oUserDaoTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.62 sec <<< FAILURE! - in models.dao.Sql2oUserDaoTest
models.dao.Sql2oUserDaoTest  Time elapsed: 0.62 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "41.84.152.6", user "rbwqysqbdiaqms", database "d9stjanqk4t4gk", SSL off
	at models.dao.Sql2oUserDaoTest.setUp(Sql2oUserDaoTest.java:24)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "41.84.152.6", user "rbwqysqbdiaqms", database "d9stjanqk4t4gk", SSL off
	at models.dao.Sql2oUserDaoTest.setUp(Sql2oUserDaoTest.java:24)

models.dao.Sql2oUserDaoTest  Time elapsed: 0.62 sec  <<< ERROR!
java.lang.NullPointerException
	at models.dao.Sql2oUserDaoTest.shutDown(Sql2oUserDaoTest.java:36)

